// <auto-generated />
namespace BigShop___.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class hamedl5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hamedl5));
        
        string IMigrationMetadata.Id
        {
            get { return "202105221643296_hamedl5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
