// <auto-generated />
namespace BigShop___.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class user_review : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_review));
        
        string IMigrationMetadata.Id
        {
            get { return "202105262235496_user_review"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
