// <auto-generated />
namespace BigShop___.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class hamedl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hamedl));
        
        string IMigrationMetadata.Id
        {
            get { return "202105221607092_hamedl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
